[package]
name = "heeranjid-node"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
heeranjid = { path = "../heeranjid", default-features = false }
napi = { version = "2", features = ["napi9"] }
napi-derive = "2"
uuid = "1"

[build-dependencies]
napi-build = "2"
