[package]
name = "heeranjid-node"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
heeranjid = { path = "../../heeranjid", default-features = false }
napi = { version = "3", features = ["napi9"] }
napi-derive = "3"
uuid = "1"

[build-dependencies]
napi-build = "2"
