import uuid

class mssql_schema:
    DESC_FLIP_TSQL: str
    DESC_GENERATORS_TSQL: str
    BULK_BACKFILL_TSQL: str
    INSTALL_ALL_DESC_TSQL: str

    @staticmethod
    def mssql_install_autofill_trigger_for_table(
        table: str, pairs: list[tuple[str, str]], kind: str
    ) -> str: ...
    @staticmethod
    def mssql_drop_autofill_trigger_for_table(table: str) -> str: ...

class HeerId:
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_str(s: str) -> "HeerId": ...
    def as_int(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def node_id(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: "HeerId") -> bool: ...
    def __le__(self, other: "HeerId") -> bool: ...
    def __gt__(self, other: "HeerId") -> bool: ...
    def __ge__(self, other: "HeerId") -> bool: ...
    def __hash__(self) -> int: ...
    @staticmethod
    def batch_to_ranjids(ids: list["HeerId"]) -> list[tuple["HeerId", "RanjId"]]: ...
    @staticmethod
    def check_ranjid_convertibility(ids: list["HeerId"]) -> list[str]: ...

class RanjId:
    @staticmethod
    def from_str(s: str) -> "RanjId": ...
    def to_uuid(self) -> uuid.UUID: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def timestamp_micros(self) -> int: ...
    @property
    def precision(self) -> str: ...
    @property
    def node_id(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: "RanjId") -> bool: ...
    def __le__(self, other: "RanjId") -> bool: ...
    def __gt__(self, other: "RanjId") -> bool: ...
    def __ge__(self, other: "RanjId") -> bool: ...
    def __hash__(self) -> int: ...
    @staticmethod
    def batch_to_heerids(ids: list["RanjId"]) -> list[tuple["RanjId", "HeerId"]]: ...
    @staticmethod
    def check_heerid_convertibility(ids: list["RanjId"]) -> list[str]: ...

class HeerIdDesc:
    def __init__(self, value: int) -> None: ...
    @staticmethod
    def from_str(s: str) -> "HeerIdDesc": ...
    @staticmethod
    def from_parts(timestamp_ms: int, node_id: int, sequence: int) -> "HeerIdDesc": ...
    def as_int(self) -> int: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def node_id(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: "HeerIdDesc") -> bool: ...
    def __le__(self, other: "HeerIdDesc") -> bool: ...
    def __gt__(self, other: "HeerIdDesc") -> bool: ...
    def __ge__(self, other: "HeerIdDesc") -> bool: ...
    def __hash__(self) -> int: ...

class RanjIdDesc:
    @staticmethod
    def from_str(s: str) -> "RanjIdDesc": ...
    @staticmethod
    def from_parts(timestamp: int, precision: str, node_id: int, sequence: int) -> "RanjIdDesc": ...
    def to_uuid(self) -> uuid.UUID: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def precision(self) -> str: ...
    @property
    def node_id(self) -> int: ...
    @property
    def sequence(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: "RanjIdDesc") -> bool: ...
    def __le__(self, other: "RanjIdDesc") -> bool: ...
    def __gt__(self, other: "RanjIdDesc") -> bool: ...
    def __ge__(self, other: "RanjIdDesc") -> bool: ...
    def __hash__(self) -> int: ...
